baseURL = 'https://opebracket.ca/'
languageCode = 'en-us'
title = 'Openbracket'
theme = 'simplog'
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
author = "TJ Gillis"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

[taxonomies]
  tag = "tags"

[params]
  subtitle = "a tj gillis braindump"
  customCSS = "@font-face {
  font-family: "fira-sans", sans-serif;
  font-weight: 400;
  font-style: normal;
} "
  adobeFontsKitId = "iyj0xgy.css"
  colorTheme = "dark"
  summary = true
  toc = true